services:
  server:
    container_name: server
    user: "1000:1000"
    restart: on-failure
    build:
      context: ./server
      target: local
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    networks:
      - ckir.io-visions
    extra_hosts:
      - "host.docker.internal:host-gateway"

  dashboard:
    container_name: dashboard
    user: "1000:1000"
    restart: on-failure
    depends_on:
      - server
    build:
      context: ./dashboard
      target: local
    volumes:
      - ./dashboard:/app
    env_file:
      - ./dashboard/.env
    ports:
      - "5173:5173"
    networks:
      - ckir.io-visions

networks:
  ckir.io-visions:
    external: true
    name: ckir.io-visions
