packages:
  - '.'
  - 'packages/*'
  - 'apps/*'

allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': true
  '@swc/core': true
  esbuild: true
  fastify-socket.io: true
  msgpackr-extract: true
  prisma: true
  vue-demi: true

minimumReleaseAgeExclude:
  - '@intlify/core-base@11.4.9'
  - '@intlify/devtools-types@11.4.9'
  - '@intlify/message-compiler@11.4.9'
  - '@intlify/shared@11.4.9'
  - '@tanstack/query-core@5.102.1'
  - '@tanstack/vue-query@5.102.1'
  - '@triplef/*'
  - vue-i18n@11.4.9
