/**
 * Curated Lucide icon allowlist for taxonomy macro-nodes (clusters,
 * communities, hubs). The model may suggest one of these names when it
 * CREATES a label (probe CREATE_NEW / remember / classify payloads); the
 * server validates against this list — an unknown name is dropped, not
 * stored. The dashboard renders the same names on the constellation's
 * macro-node dots. Kebab-case, exactly as Lucide publishes them.
 */
export const TAXONOMY_ICON_ALLOWLIST = [
  'activity',
  'plane',
  'anchor',
  'apple',
  'archive',
  'atom',
  'banknote',
  'bike',
  'bird',
  'bitcoin',
  'book',
  'book-open',
  'bot',
  'brain',
  'briefcase',
  'brush',
  'bug',
  'building',
  'cake',
  'calculator',
  'calendar',
  'camera',
  'car',
  'cat',
  'chart-line',
  'chef-hat',
  'clapperboard',
  'cloud',
  'code',
  'coffee',
  'cog',
  'coins',
  'compass',
  'contact',
  'cpu',
  'credit-card',
  'dumbbell',
  'factory',
  'file-text',
  'film',
  'fish',
  'flag',
  'flask-conical',
  'flower-2',
  'volleyball',
  'gamepad-2',
  'gem',
  'gift',
  'globe',
  'graduation-cap',
  'guitar',
  'hammer',
  'handshake',
  'headphones',
  'heart-pulse',
  'house',
  'hospital',
  'key',
  'landmark',
  'laptop',
  'leaf',
  'lightbulb',
  'map-pin',
  'medal',
  'mic',
  'microscope',
  'mountain',
  'music',
  'newspaper',
  'package',
  'palette',
  'paw-print',
  'phone',
  'piggy-bank',
  'rocket',
  'scale',
  'server',
  'shield',
  'ship',
  'shirt',
  'shopping-bag',
  'sprout',
  'star',
  'stethoscope',
  'sun',
  'trophy',
  'truck',
  'tv',
  'umbrella',
  'utensils',
  'wallet',
  'wifi',
  'wrench',
  'zap',
] as const;

/** One allowlisted icon name. */
export type TaxonomyIconName = (typeof TAXONOMY_ICON_ALLOWLIST)[number];
