allowBuilds:
  '"': true
  ',': true
  /: true
  '@': true
  '@nestjs/core': false
  '@prisma/engines': false
  '@scarf/scarf': false
  '[': true
  ']': true
  a: true
  c: true
  e: true
  fastify-socket.io: false
  g: true
  h: true
  i: true
  j: true
  l: true
  m: true
  msgpackr-extract: false
  n: true
  o: true
  p: true
  prisma: false
  r: true
  s: true
  sharp: false
  t: true
