export const COMPARE_INSTRUCTIONS = [
  'MODE: COMPARE',
  '',
  'Goal: produce a JSON object that the dashboard will render as an HTML card.',
  '',
  'MANDATORY RULES:',
  "1. The latest user message contains the user's actual question AND the attached images.",
  '2. If the user asked a question, answer it DIRECTLY in sectionContent first. The answer must be a single coherent paragraph, not a list of options or variants.',
  '3. Only if the user did NOT ask a question, compare the visible content of the two images.',
  '4. sectionContent is the ONLY place for your main text response; it must be a single string value, not an object or array. If the response spans multiple paragraphs, use the escaped newline sequence \\n between paragraphs — never a literal line break inside the JSON string.',
  '5. Do not output multiple possibilities. Commit to the most likely answer visible in the images and explain briefly why.',
  '6. Base everything strictly on what is visible in the images.',
  '',
  'Required fields:',
  '- category: a short category label such as Comparison, Before/After, A/B.',
  '- title: a concise, descriptive title.',
  '- subtitle: an optional one-line summary (empty string if not needed).',
  '- sectionContent: a single string containing the main answer or comparison. It will be inserted into the template as plain text.',
  '- keyFindings: an array of 0–5 short supporting observations. Each entry MUST be an object with exactly one key: "text". Example: [{"text":"The left image shows the car from the front."},{"text":"The right image shows the car from the rear."}]',
  '- sources: an array of source objects. Empty array unless tool results provide real sources.',
  '',
  'Rules:',
  '- Write the entire response, including title, sectionContent, and keyFindings, in the same language as the latest user message.',
  '- Never emit placeholder text such as "undefined", "null", "none", or "n/a". Use an empty string or empty array instead.',
  '',
  'Examples:',
  '- User: "Which one is taller?" → sectionContent: "The figure on the left is taller. In both images the subjects stand side by side and the top of the left figure\'s head is clearly higher."',
  '- User: "What are the differences?" → sectionContent: "The left image shows a red car and the right image shows the same car in blue. The composition and background are otherwise identical."',

  'FINAL REMINDER:',
  '- Base everything strictly on what is visible in the images.',
].join('\n');
