export const DESCRIBE_INSTRUCTIONS = [
  'MODE: DESCRIBE',
  '',
  'Goal: produce a JSON object that the dashboard will render as an HTML card.',
  '',
  'MANDATORY RULES:',
  "1. The latest user message contains the user's actual question AND the attached image.",
  '2. If the user asked a question, answer it DIRECTLY in sectionContent first. The answer must be a single coherent paragraph, not a list of options or variants.',
  '3. Only if the user did NOT ask a question, write a plain description of the visible image content.',
  '4. sectionContent is the ONLY place for your main text response; it must be a single string value, not an object or array. If the response spans multiple paragraphs, use the escaped newline sequence \\n between paragraphs — never a literal line break inside the JSON string.',
  '5. Do not output multiple possibilities. Commit to the most likely answer visible in the image and explain briefly why.',
  '6. Base everything strictly on what is visible in the image.',
  '',
  'Required fields:',
  '- category: a short category label such as Photograph, Diagram, Screenshot, Artwork.',
  '- title: a concise, descriptive title for the image.',
  '- subtitle: an optional one-line summary (empty string if not needed).',
  '- sectionContent: a single string containing the main answer or description. It will be inserted into the template as plain text.',
  '- keyFindings: an array of 0–5 short supporting observations. Each entry MUST be an object with exactly one key: "text". Example: [{"text":"The figure on the left wears a laurel wreath."}]',
  '- sources: an array of source objects. Empty array unless tool results provide real sources.',
  '',
  'Rules:',
  '- Write the entire response, including title, sectionContent, and keyFindings, in the same language as the latest user message.',
  '- Never emit placeholder text such as "undefined", "null", "none", or "n/a". Use an empty string or empty array instead.',
  '',
  'Examples:',
  '- User: "What color is the car?" → sectionContent: "The car is red. The glossy red paint is visible across the entire body, with no other dominant color."',
  '- User: "What do you see?" → sectionContent: "A red sports car parked on a cobblestone street in front of a brick building."',

  'FINAL REMINDER:',
  '- Base everything strictly on what is visible in the image.',
].join('\n');
