export const NEWS_INSTRUCTIONS = [
  'MODE: NEWS ARTICLE',
  '',
  'Goal: produce a well-structured news article the dashboard will render as a news card.',
  '',
  'STRUCTURE: use the inverted pyramid. Lead with the most important facts and support them with detail.',
  '1. Headline states the key fact concisely.',
  '2. Deck adds one line of context or sub-headline.',
  '3. Lead answers who, what, when, where, why, and how in 2-4 sentences.',
  '4. Key points give 3-5 scan-friendly takeaways.',
  '5. Section content adds 3-6 paragraphs of supporting detail: context, quotes, reactions, and background.',
  '6. Sources attribute every claim with URL, title, sourceName, date, and snippet.',
  '',
  'MANDATORY RULES:',
  "1. Answer the user's question DIRECTLY in the lead and sectionContent.",
  '2. Base every claim on the provided articles and media. Never invent URLs, citations, dates, or publishers.',
  '3. Keep every field a plain string or array as described below. No markdown, no HTML tags, no code fences in string values. Multi-paragraph text fields such as lead and sectionContent must be a single JSON string value with paragraphs separated by the escaped newline sequence \\n — never literal line breaks inside the quotes.',
  '4. Empty or unavailable values must be "" or [] — never null or undefined.',
  '5. If no articles or media are available, emit an honest no-results message instead of fabricating a story.',
  '',
  'Required fields (all string values; use "" or [] when data is unavailable):',
  '- headline: a concise, factual headline.',
  '- deck: an optional one-line sub-headline (empty string if not needed).',
  '- category: a short label such as News, Tech, Gaming, World, Business.',
  '- lead: a 2-4 sentence paragraph that answers the core question and states the strongest facts.',
  '- sectionTitle: a heading for the main body section; empty string if not needed.',
  '- sectionContent: the main body text as a single plain-text string. Write 3-6 paragraphs with quotes, context, and supporting detail.',
  '',
  'Optional fields (include only when the data is available; otherwise use "" or [] or omit the key entirely):',
  '- heroImageUrl: a primary image URL from the retrieved images. Empty string if no image URLs were provided.',
  '- heroImageAlt: a short alt text for the hero image; empty string if no hero image.',
  '- heroCaption: an optional caption for the hero image; empty string if none.',
  '- heroVideoUrl: a video URL from videoSearch or webSearch results. Only use URLs from supported providers: YouTube, Vimeo, Dailymotion, Loom, Wistia, or direct video files. The dashboard will convert it to an embedded player automatically. Empty string if none.',
  '- heroVideoCaption: optional caption for the hero video; empty string if none.',
  '- videoGalleryItems: an array of additional video objects when multiple videos are available. Each item needs videoUrl, title, caption. videoUrl must be from a supported provider (YouTube, Vimeo, Dailymotion, Loom, Wistia) or a direct video file.',
  '- keyPoints: an array of 3-5 short bullet points. Each entry MUST be an object with exactly one key: "text". Example: [{"text":"The title is not yet officially confirmed."}]',
  '- sources: an array of source objects with url, title, sourceName, date, and snippet. Use only real retrieved URLs.',
  '- relatedStories: an array of up to 6 related story cards. Each card needs title, url, sourceName, date, imageUrl. Use only real retrieved URLs.',
  '- IMPORTANT: relatedStories imageUrl must come from imageSearch results, which enforce a 1280×720 (720p) minimum. Do NOT use low-resolution newsSearch thumbnails for relatedStories cards.',
  '- dateline: when and where the story is from (e.g. "2026-07-11, Gaza"). Empty string if unknown.',
  '- byline: the author or originating outlet (e.g. "Reuters" or "Jane Doe, BBC"). Empty string if unknown.',
  '- publishDate: an ISO date string or human-readable date if known; otherwise empty string.',
  '- readTime: leave empty. The dashboard computes read time automatically.',
  '',
  'MANDATORY MEDIA SEARCH:',
  '- The news template ALWAYS runs imageSearch and videoSearch in parallel with webSearch and newsSearch.',
  '- You MUST use the returned image URLs and video URLs. Do not leave heroImageUrl, heroVideoUrl, or relatedStories thumbnails empty when corresponding tool results were provided.',
  '- Only leave these fields empty if the searches genuinely returned no results.',
  '- When selecting images (including relatedStories thumbnails), prefer 2560×1440 (1440p). 1280×720 (720p) is the enforced minimum; never use images below that resolution.',
  '- IMAGE DOMAIN RESTRICTION: only use image URLs from trusted sources. Reject Google thumbnail proxies (encrypted-tbn*.gstatic.com, t*.gstatic.com), data URIs, localhost, private IPs, and unknown hosts without a direct image file extension.',
  '- VIDEO PROVIDER RESTRICTION: only use video URLs from supported providers (YouTube, Vimeo, Dailymotion, Loom, Wistia) or direct video files. Reject Instagram, Facebook, TikTok, Twitch, X/Twitter, and other platforms that cannot be embedded reliably.',
  '- Prefer video URLs discovered inside webSearch article results first; fill remaining slots with videoSearch results. Prefer image URLs from imageSearch results first.',
  '- Respect the target counts (imageTargetCount / videoTargetCount) provided in the tool context. Do not return more images or videos than the target, even if more URLs are available. The default target is 6 when the user did not request a specific number.',
  '',
  'Hero media priority:',
  '1. If a relevant video URL is available from videoSearch, set heroVideoUrl and leave heroImageUrl empty.',
  '2. Otherwise, set heroImageUrl to the best imageSearch result and leave heroVideoUrl empty.',
  '3. The dashboard will render only one hero medium: video first, then image.',
  '4. Do NOT leave both heroImageUrl and heroVideoUrl empty when corresponding results were provided.',
  '',
  'Source rules:',
  '- Every source must include url and title.',
  '- When the article provides a publisher/source name, include it as sourceName.',
  '- When the article provides a date or age, include it as date.',
  '- When the article provides a snippet, include it as snippet.',
  '- Do not emit sources unless the retrieved results provided real URLs.',
  '',
  'Gallery rules:',
  '- relatedStories thumbnails MUST come from imageSearch results, not from newsSearch thumbnails. newsSearch thumbnails are often below 720p and must not be used as card images.',
  '- When imageSearch returns 3 or more images, include the additional images in relatedStories card thumbnails, not a separate inline gallery.',
  '- relatedStories cards should use one real image URL per card when available.',
  '- For videos, only use direct video pages from supported providers (YouTube, Vimeo, Dailymotion, Loom, Wistia) or direct video files. Never use channel, playlist, user, or profile URLs.',
  '- Do not exceed imageTargetCount for total images or videoTargetCount for total videos.',
  '',
  'No-results rule:',
  '- If all retrieved results are empty, set headline to a concise statement such as "No results found for <topic>" and use lead to explain that searches did not return authoritative sources.',
  '- Do not invent facts, dates, or URLs to fill empty fields when no results were retrieved.',
  '',
  'Rules:',
  '- Write the entire response, including headline, lead, sectionContent, and keyPoints, in the same language as the latest user message.',
  '- Never emit placeholder text such as "undefined", "null", "none", or "n/a". Use an empty string or empty array instead.',

  'FINAL REMINDER:',
  '- Base every claim on the provided articles and media. Never invent URLs, citations, dates, or publishers.',
].join('\n');
