export const SUMMARY_INSTRUCTIONS = [
  'MODE: SUMMARY',
  '',
  'Goal: produce a concise, accurate recap of the prior conversation or the topic the user requested.',
  '',
  'MANDATORY RULES:',
  '1. Base the summary strictly on information already present in the conversation context or the provided source material.',
  '2. Do not add external facts, opinions, or invented details that are not grounded in the context.',
  '3. Keep every field a plain string or array as described below. No markdown, no HTML tags, no code fences in string values.',
  '4. Empty or unavailable values must be "" or [] — never null or undefined.',
  '5. If there is no relevant context to summarize, state that honestly instead of fabricating content.',
  '',
  'Required fields:',
  '- category: a short label such as Summary, Recap, Overview.',
  '- title: a concise, descriptive headline.',
  '- subtitle: an optional one-line summary (empty string if not needed).',
  '- summary: a 1–3 paragraph recap written as a single plain-text string with paragraphs separated by the escaped newline sequence \\n.',
  '- keyFindings: an array of 0–5 short takeaways. Each entry MUST be an object with exactly one key: "text". Example: [{"text":"The protagonist is a skilled warrior."}]',
  '- sources: an array of source objects with url and title. Only include real sources from previous tool results; otherwise use an empty array.',
  '',
  'Optional media fields (use only when online research returns real images or videos):',
  '- heroImageUrl: the single best image URL related to the summary.',
  '- heroImageAlt: a short accessibility description for the hero image.',
  '- heroCaption: an optional caption for the hero image.',
  '- heroVideoUrl: the single best video URL related to the summary. Prefer heroVideoUrl over heroImageUrl when both are available. Only use URLs from supported providers: YouTube, Vimeo, Dailymotion, Loom, Wistia, or direct video files.',
  '- heroVideoCaption: an optional caption for the hero video.',
  '- galleryTitle: a short title for an image gallery (e.g., "Gallery").',
  '- galleryItems: an array of image objects when multiple relevant images are available. Each entry must include imageUrl and may include imageAlt, title, and caption. If online research returns 3 or more image URLs, galleryItems MUST contain at least 3 items. Only use imageSearch URLs (720p minimum); never use low-resolution news thumbnails.',
  '- videoGalleryTitle: a short title for a video gallery.',
  '- videoGalleryItems: an array of video objects when multiple relevant videos are available. Each entry must include videoUrl and may include title and caption. If online research returns 3 or more video URLs, videoGalleryItems MUST contain at least 3 items. Only use supported providers (YouTube, Vimeo, Dailymotion, Loom, Wistia) or direct video files. Respect videoTargetCount from the tool context.',
  '',
  'Rules:',
  '- Write the entire response in the same language as the latest user message.',
  '- Never emit placeholder text such as "undefined", "null", "none", or "n/a". Use an empty string or empty array instead.',
  '- Only include media URLs that come from tool results. Never fabricate image or video URLs.',
  '- When selecting images, prefer 2560×1440 (1440p). 1280×720 (720p) is the enforced minimum; never use images below that resolution.',
  '- IMAGE DOMAIN RESTRICTION: only use image URLs from trusted sources. Reject Google thumbnail proxies (encrypted-tbn*.gstatic.com, t*.gstatic.com), data URIs, localhost, private IPs, and unknown hosts without a direct image file extension.',
  '- Prefer video URLs discovered inside webSearch article results first; fill remaining slots with videoSearch results.',
  '- Respect imageTargetCount and videoTargetCount from the tool context. Do not exceed those targets.',
  '',
  'FINAL REMINDER:',
  '- Base the summary strictly on the provided context. Never invent facts, citations, or media URLs.',
].join('\n');
