import {
  Activity,
  Anchor,
  Apple,
  Archive,
  Atom,
  Banknote,
  Bike,
  Bird,
  Bitcoin,
  Book,
  BookOpen,
  Bot,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  Cat,
  ChartLine,
  ChefHat,
  Clapperboard,
  Cloud,
  Code,
  Coffee,
  Cog,
  Coins,
  Compass,
  Contact,
  Cpu,
  CreditCard,
  Dumbbell,
  Factory,
  FileText,
  Film,
  Fish,
  Flag,
  FlaskConical,
  Flower2,
  Gamepad2,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Guitar,
  Hammer,
  Handshake,
  Headphones,
  HeartPulse,
  Hospital,
  House,
  Key,
  Landmark,
  Laptop,
  Leaf,
  Lightbulb,
  MapPin,
  Medal,
  Mic,
  Microscope,
  Mountain,
  Music,
  Newspaper,
  Package,
  Palette,
  PawPrint,
  Phone,
  PiggyBank,
  Plane,
  Rocket,
  Scale,
  Server,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Utensils,
  Volleyball,
  Wallet,
  Wifi,
  Wrench,
  Zap,
} from '@lucide/icons';

/** One Lucide SVG child node: `[tag, attributes]`. */
export type TaxonomyIconNode = readonly [
  string,
  Record<string, string | number>,
];

/**
 * The curated taxonomy icon set — kebab name → Lucide node tuples. MUST
 * stay aligned with TAXONOMY_ICON_ALLOWLIST in @triplef/agent (the server
 * validates against that list and the model writes names from it). Explicit
 * named imports keep the bundle tree-shaken (no full-icons map import).
 */
export const TAXONOMY_ICON_NODES: Readonly<
  Record<string, readonly TaxonomyIconNode[]>
> = {
  activity: Activity.node,
  anchor: Anchor.node,
  apple: Apple.node,
  archive: Archive.node,
  atom: Atom.node,
  banknote: Banknote.node,
  bike: Bike.node,
  bird: Bird.node,
  bitcoin: Bitcoin.node,
  book: Book.node,
  'book-open': BookOpen.node,
  bot: Bot.node,
  brain: Brain.node,
  briefcase: Briefcase.node,
  brush: Brush.node,
  bug: Bug.node,
  building: Building.node,
  cake: Cake.node,
  calculator: Calculator.node,
  calendar: Calendar.node,
  camera: Camera.node,
  car: Car.node,
  cat: Cat.node,
  'chart-line': ChartLine.node,
  'chef-hat': ChefHat.node,
  clapperboard: Clapperboard.node,
  cloud: Cloud.node,
  code: Code.node,
  coffee: Coffee.node,
  cog: Cog.node,
  coins: Coins.node,
  compass: Compass.node,
  contact: Contact.node,
  cpu: Cpu.node,
  'credit-card': CreditCard.node,
  dumbbell: Dumbbell.node,
  factory: Factory.node,
  'file-text': FileText.node,
  film: Film.node,
  fish: Fish.node,
  flag: Flag.node,
  'flask-conical': FlaskConical.node,
  'flower-2': Flower2.node,
  'gamepad-2': Gamepad2.node,
  gem: Gem.node,
  gift: Gift.node,
  globe: Globe.node,
  'graduation-cap': GraduationCap.node,
  guitar: Guitar.node,
  hammer: Hammer.node,
  handshake: Handshake.node,
  headphones: Headphones.node,
  'heart-pulse': HeartPulse.node,
  hospital: Hospital.node,
  house: House.node,
  key: Key.node,
  landmark: Landmark.node,
  laptop: Laptop.node,
  leaf: Leaf.node,
  lightbulb: Lightbulb.node,
  'map-pin': MapPin.node,
  medal: Medal.node,
  mic: Mic.node,
  microscope: Microscope.node,
  mountain: Mountain.node,
  music: Music.node,
  newspaper: Newspaper.node,
  package: Package.node,
  palette: Palette.node,
  'paw-print': PawPrint.node,
  phone: Phone.node,
  'piggy-bank': PiggyBank.node,
  plane: Plane.node,
  rocket: Rocket.node,
  scale: Scale.node,
  server: Server.node,
  shield: Shield.node,
  ship: Ship.node,
  shirt: Shirt.node,
  'shopping-bag': ShoppingBag.node,
  sprout: Sprout.node,
  star: Star.node,
  stethoscope: Stethoscope.node,
  sun: Sun.node,
  trophy: Trophy.node,
  truck: Truck.node,
  tv: Tv.node,
  umbrella: Umbrella.node,
  utensils: Utensils.node,
  volleyball: Volleyball.node,
  wallet: Wallet.node,
  wifi: Wifi.node,
  wrench: Wrench.node,
  zap: Zap.node,
};
