#!/bin/sh
. "$(dirname "$0")/prepare.sh"

check_working_directory
check_branch_identifier

# makes sure all dependencies are up to date
info 'pn -r ncu:validate' && pn -r ncu:validate

info 'pn -r lint' && pn -r lint

# dry run tests
info 'pn -r test --silent' && pn -r test --silent
info 'pn -r test:cov' && pn -r test:cov

# no unused exports
info 'pn -r lint:unused' && pn -r lint:unused

# add known orphans to .depcruiserrc.json
info 'pn -r depcruise' && pn -r depcruise

# whitelist by adding the package to depcheckrc.yml
info 'pn -r depcheck' && pn -r depcheck
