name: NON_RELEASE_CI

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches-ignore: [main]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      production: false
      upload-coverage: false
      upload-artifacts: false
